
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CHAR COMMA DTYPE EQUALS ID NUMBER SEMICOLON STRING\n    declaration : DTYPE list SEMICOLON\n    list        : ID COMMA list\n                | ID      \n    '
    
_lr_action_items = {'DTYPE':([0,],[2,]),'$end':([1,5,],[0,-1,]),'ID':([2,6,],[4,4,]),'SEMICOLON':([3,4,7,],[5,-3,-2,]),'COMMA':([4,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaration':([0,],[1,]),'list':([2,6,],[3,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaration","S'",1,None,None,None),
  ('declaration -> DTYPE list SEMICOLON','declaration',3,'p_declaration','javaVarDecParse.py',8),
  ('list -> ID COMMA list','list',3,'p_declaration','javaVarDecParse.py',9),
  ('list -> ID','list',1,'p_declaration','javaVarDecParse.py',10),
]
