
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA DTYPE ID LBRACE PRIVATE PROTECTED PUBLIC RBRACE SEMICOLON STATIC\n    funcDeclaration : accessModifier statickw DTYPE funcname LBRACE params RBRACE SEMICOLON\n                    | accessModifier DTYPE funcname LBRACE params RBRACE SEMICOLON \n    \n    accessModifier : PUBLIC\n                   | PROTECTED\n                   | PRIVATE\n                   | \n    \n    statickw : STATIC\n    \n    funcname : ID\n    \n    params : DTYPE ID COMMA params\n           | DTYPE ID \n           |\n    '
    
_lr_action_items = {'PUBLIC':([0,],[3,]),'PROTECTED':([0,],[4,]),'PRIVATE':([0,],[5,]),'DTYPE':([0,2,3,4,5,6,8,13,14,21,],[-6,7,-3,-4,-5,9,-7,15,15,15,]),'STATIC':([0,2,3,4,5,],[-6,8,-3,-4,-5,]),'$end':([1,22,23,],[0,-2,-1,]),'ID':([7,9,15,],[11,11,18,]),'LBRACE':([10,11,12,],[13,-8,14,]),'RBRACE':([13,14,16,17,18,21,24,],[-11,-11,19,20,-10,-11,-9,]),'COMMA':([18,],[21,]),'SEMICOLON':([19,20,],[22,23,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'funcDeclaration':([0,],[1,]),'accessModifier':([0,],[2,]),'statickw':([2,],[6,]),'funcname':([7,9,],[10,12,]),'params':([13,14,21,],[16,17,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> funcDeclaration","S'",1,None,None,None),
  ('funcDeclaration -> accessModifier statickw DTYPE funcname LBRACE params RBRACE SEMICOLON','funcDeclaration',8,'p_funcDeclaration','javaFuncDecParse.py',8),
  ('funcDeclaration -> accessModifier DTYPE funcname LBRACE params RBRACE SEMICOLON','funcDeclaration',7,'p_funcDeclaration','javaFuncDecParse.py',9),
  ('accessModifier -> PUBLIC','accessModifier',1,'p_accessModifier','javaFuncDecParse.py',15),
  ('accessModifier -> PROTECTED','accessModifier',1,'p_accessModifier','javaFuncDecParse.py',16),
  ('accessModifier -> PRIVATE','accessModifier',1,'p_accessModifier','javaFuncDecParse.py',17),
  ('accessModifier -> <empty>','accessModifier',0,'p_accessModifier','javaFuncDecParse.py',18),
  ('statickw -> STATIC','statickw',1,'p_statickw','javaFuncDecParse.py',27),
  ('funcname -> ID','funcname',1,'p_funcname','javaFuncDecParse.py',36),
  ('params -> DTYPE ID COMMA params','params',4,'p_params','javaFuncDecParse.py',43),
  ('params -> DTYPE ID','params',2,'p_params','javaFuncDecParse.py',44),
  ('params -> <empty>','params',0,'p_params','javaFuncDecParse.py',45),
]
